services:
    web:
        image: ghcr.io/vironauticsgroup/keeperpass/web:latest
        container_name: keeperpass-web
        restart: always
        ports:
            - "80"
        networks:
            - keeperpass-network

    welcome:
        image: ghcr.io/vironauticsgroup/keeperpass/welcome:latest
        container_name: keeperpass-welcome
        restart: always
        ports:
            - "80"
        networks:
            - keeperpass-network

networks:
    keeperpass-network:
        driver: bridge
